// Code generated by MockGen. DO NOT EDIT.
package mocks

import (
	"github.com/VoLKoDaV13579/GoToDoList/internal/model"
	"github.com/stretchr/testify/mock"
)

// MockTodoService is a mock of TodoService interface
type MockTodoService struct {
	mock.Mock
}

// CreateTodo mocks the CreateTodo method
func (m *MockTodoService) CreateTodo(req *model.CreateTodoRequest) (*model.Todo, error) {
	args := m.Called(req)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*model.Todo), args.Error(1)
}

// GetTodoByID mocks the GetTodoByID method
func (m *MockTodoService) GetTodoByID(id uint) (*model.Todo, error) {
	args := m.Called(id)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*model.Todo), args.Error(1)
}

// GetAllTodos mocks the GetAllTodos method
func (m *MockTodoService) GetAllTodos(filter *model.TodoFilter) (*model.TodoListResponse, error) {
	args := m.Called(filter)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*model.TodoListResponse), args.Error(1)
}

// UpdateTodo mocks the UpdateTodo method
func (m *MockTodoService) UpdateTodo(id uint, req *model.UpdateTodoRequest) (*model.Todo, error) {
	args := m.Called(id, req)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*model.Todo), args.Error(1)
}

// DeleteTodo mocks the DeleteTodo method
func (m *MockTodoService) DeleteTodo(id uint) error {
	args := m.Called(id)
	return args.Error(0)
}

// UpdateTodoStatus mocks the UpdateTodoStatus method
func (m *MockTodoService) UpdateTodoStatus(id uint, status model.TodoStatus) (*model.Todo, error) {
	args := m.Called(id, status)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*model.Todo), args.Error(1)
}
