// Code generated by MockGen. DO NOT EDIT.
package mocks

import (
	"github.com/VoLKoDaV13579/GoToDoList/internal/model"
	"github.com/stretchr/testify/mock"
)

// MockTodoRepository is a mock of TodoRepository interface
type MockTodoRepository struct {
	mock.Mock
}

// Create mocks the Create method
func (m *MockTodoRepository) Create(todo *model.Todo) error {
	args := m.Called(todo)
	return args.Error(0)
}

// GetByID mocks the GetByID method
func (m *MockTodoRepository) GetByID(id uint) (*model.Todo, error) {
	args := m.Called(id)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).(*model.Todo), args.Error(1)
}

// GetAll mocks the GetAll method
func (m *MockTodoRepository) GetAll(filter *model.TodoFilter) ([]model.Todo, int64, error) {
	args := m.Called(filter)
	if args.Get(0) == nil {
		return nil, args.Get(1).(int64), args.Error(2)
	}
	return args.Get(0).([]model.Todo), args.Get(1).(int64), args.Error(2)
}

// Update mocks the Update method
func (m *MockTodoRepository) Update(todo *model.Todo) error {
	args := m.Called(todo)
	return args.Error(0)
}

// Delete mocks the Delete method
func (m *MockTodoRepository) Delete(id uint) error {
	args := m.Called(id)
	return args.Error(0)
}
